git:
  depth: 1

dist: trusty
sudo: required

addons:
  apt:
    update: true

before_script:
  - sudo snap install snapcraft --channel edge/bases
  - sudo apt-get install -y cloud-image-utils qemu-kvm

script:
  - SNAPCRAFT_BUILD_ENVIRONMENT=qemu snapcraft
