git:
  depth: 1

dist: trusty
sudo: required

addons:
  apt:
    update: true

before_script:
  - sudo apt-get install -y cloud-image-utils qemu-kvm snapd cpu-checker
  - sudo snap install snapcraft --channel edge/bases --classic

script:
  - sudo kvm-ok
  - SNAPCRAFT_BUILD_ENVIRONMENT=qemu /snap/bin/snapcraft version
  - SNAPCRAFT_BUILD_ENVIRONMENT=qemu /snap/bin/snapcraft --debug
